#!/usr/bin/env python3
"""Build conversation-level TAMV feature tables for CGA."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


META_COLUMNS = {
    "document_id",
    "genre",
    "corpus",
    "total_clauses",
    "meta_has_derailed",
    "meta_max_toxicity",
    "meta_mean_toxicity",
    "meta_num_turns",
}


def parse_args() -> argparse.Namespace:
    code_dir = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Build CGA TAMV feature tables from existing profiles.")
    parser.add_argument(
        "--profiles",
        type=Path,
        default=code_dir / "output" / "tamv_profiles.csv",
        help="Input TAMV profile CSV generated by the extraction pipeline.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=code_dir / "output" / "toxicity_protocol" / "cga_wiki_split_manifest.tsv",
        help="Conversation-level split manifest from the CGA toxicity protocol.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=code_dir / "output" / "cga_feature_building",
        help="Directory for the feature-building artifacts.",
    )
    return parser.parse_args()


def load_tables(profiles_path: Path, manifest_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    if not profiles_path.exists():
        raise FileNotFoundError(f"Missing TAMV profiles: {profiles_path}")
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing CGA manifest: {manifest_path}")

    profiles = pd.read_csv(profiles_path, low_memory=False)
    manifest = pd.read_csv(manifest_path, sep="\t")
    return profiles, manifest


def detect_feature_columns(frame: pd.DataFrame) -> list[str]:
    return [c for c in frame.columns if c not in META_COLUMNS]


def build_feature_table(profiles: pd.DataFrame, manifest: pd.DataFrame) -> pd.DataFrame:
    cga = profiles[profiles["corpus"] == "cga_wiki"].copy()
    if cga.empty:
        raise ValueError("No CGA-WIKI rows were found in the TAMV profile table.")

    feature_cols = detect_feature_columns(cga)
    merged = cga.merge(
        manifest,
        left_on="document_id",
        right_on="conversation_id",
        how="inner",
        validate="one_to_one",
    )

    missing = set(manifest["conversation_id"]) - set(merged["conversation_id"])
    if missing:
        raise ValueError(f"Manifest rows without TAMV features: {len(missing)} conversations")

    cga_cols = ["document_id", "genre", "corpus", "split", "label", "label_binary"]
    meta_cols = [
        "total_clauses",
        "meta_has_derailed",
        "meta_max_toxicity",
        "meta_mean_toxicity",
        "meta_num_turns",
    ]
    ordered = cga_cols + meta_cols + feature_cols
    return merged[ordered].sort_values(["split", "document_id"]).reset_index(drop=True)


def write_outputs(frame: pd.DataFrame, output_dir: Path, source_profiles: Path, source_manifest: Path) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "combined": output_dir / "cga_wiki_tamv_features.tsv",
        "summary": output_dir / "cga_wiki_feature_summary.tsv",
        "report": output_dir / "cga_wiki_feature_report.txt",
        "config": output_dir / "cga_wiki_feature_config.json",
    }

    frame.to_csv(paths["combined"], sep="\t", index=False)
    frame.groupby("split").agg(
        conversations=("document_id", "count"),
        derailed=("label_binary", "sum"),
        mean_clauses=("total_clauses", "mean"),
        mean_max_toxicity=("meta_max_toxicity", "mean"),
    ).reset_index().to_csv(paths["summary"], sep="\t", index=False)

    feature_cols = [c for c in frame.columns if c not in cga_nonfeature_columns()]
    report_lines = [
        "CGA TAMV FEATURE BUILDING REPORT",
        "=" * 60,
        f"Conversations: {len(frame)}",
        f"Derailed: {int(frame['label_binary'].sum())}",
        f"Civil: {int((1 - frame['label_binary']).sum())}",
        f"Feature columns: {len(feature_cols)}",
        f"Split coverage: {frame['split'].value_counts().to_dict()}",
        "",
        "Checks",
        "-" * 40,
        f"Unique conversation ids: {frame['document_id'].nunique()}",
        f"Label/split consistency: {not frame[['document_id', 'split']].duplicated().any()}",
    ]
    paths["report"].write_text("\n".join(report_lines) + "\n", encoding="utf-8")

    config = {
        "source_profiles": str(source_profiles),
        "source_manifest": str(source_manifest),
        "feature_rows": int(len(frame)),
        "feature_columns": int(len(feature_cols)),
        "splits": frame["split"].value_counts().to_dict(),
    }
    paths["config"].write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return paths


def cga_nonfeature_columns() -> set[str]:
    return {
        "document_id",
        "genre",
        "corpus",
        "split",
        "label",
        "label_binary",
        "total_clauses",
        "meta_has_derailed",
        "meta_max_toxicity",
        "meta_mean_toxicity",
        "meta_num_turns",
    }


def main() -> None:
    args = parse_args()
    profiles, manifest = load_tables(args.profiles, args.manifest)
    frame = build_feature_table(profiles, manifest)
    paths = write_outputs(frame, args.output_dir, args.profiles, args.manifest)

    print(f"Wrote feature table: {paths['combined']}")
    print(f"Wrote summary: {paths['summary']}")
    print(f"Wrote report: {paths['report']}")


if __name__ == "__main__":
    main()
